#!/bin/sh

DOCKER="docker run -it --rm -e DISPLAY=$DISPLAY"
MOUNTS="-v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/john/Pictures:/home/john/Pictures \
    -v /home/john/Photos:/home/john/Photos \
    -v /home/john/working:/home/john/working \
    -v /home/john/.local:/home/john/.local \
    -v /home/john/.config:/home/john/.config"
IMAGE="photos"

if [ $# -eq 0 ]; then
    $DOCKER $MOUNTS $IMAGE
else
    $DOCKER $MOUNTS $IMAGE su - -c "$@" john
fi

